#include "xil_io.h"
#include "eth_init.h"


void ethernet_init(){ //init 10G ethernet
	//STARTUP
	Xil_Out32(ETH_BASE_ADDR + CONFIG_MANAGEMENT_ADDR, 0x45);
	//RESET_MAC_RX
	Xil_Out32(ETH_BASE_ADDR + RECEIVER_ADDR, 0x90000000);
	//RESET_MAC_TX
	Xil_Out32(ETH_BASE_ADDR + TRANSMITTER_ADDR, 0x90000000);
	//MDIO_ADDR_1
	Xil_Out32(ETH_BASE_ADDR + MDIO_CONTROL, 0x2000);
	//MDIO_WR
	//MDIO_RD_1
	Xil_Out32(ETH_BASE_ADDR + MDIO_CONTROL, 0x20);
	//MDIO_ADDR
	Xil_Out32(ETH_BASE_ADDR + MDIO_CONTROL, 0x20);
	//MDIO_RD
	//MDIO_POLL_CHECK
	//MDIO_CHECK_DATA
	//Xil_Out32(ETH_BASE_ADDR + MDIO_RX_DATA, 0x20);

}
